name: Build / Lint Check / Format Check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - run: dotnet build
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.403
      - name: Temporary workaround
        run: dotnet new globaljson --sdk-version 6.0.403 --roll-forward minor
      - name: Install Tools
        run: dotnet tool restore
      - run: dotnet dotnet-fsharplint lint JimBroBot.fsproj
  format_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Install Tools
        run: dotnet tool restore
      - run: dotnet fantomas --check .